name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: happycoder07/backend:latest
          build-args: |
            MONGO_URI=${{ secrets.MONGO_URI }}
            EXPRESS_PORT=${{ secrets.EXPRESS_PORT }}
          push: false  # Build the image but do not push yet

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: happycoder07/backend:latest
          push: true  # Push the built image to Docker Hub

      - name: Logout from Docker Hub
        run: docker logout
